name: Deploy with Tag

on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: functions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: 20.x
        cache: "npm"
        cache-dependency-path: functions/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test:once

    - name: Build
      run: npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions:lineup,functions:email,functions:transactions
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}