name: Deploy with Tag

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: functions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 22.x

      - name: Cache npm dependencies
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:once

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:lineup,functions:email,functions:transactions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
