name: Main Branch Checks

on:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: functions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Setup Bun CLI
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun run test:once

      - name: Build
        run: bun run build
