name: Main Branch Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    working-directory: functions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: 20.x
        cache: "npm"
        cache-dependency-path: functions/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test:once

    - name: Build
      run: npm run build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: lib
        path: functions/lib
  
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Download Production Artifact
      uses: actions/download-artifact@master
      with:
        name: lib
        path: functions/lib

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions:lineup,functions:email,functions:transactions
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}